### ISSUE TITLE
Sendgrid rejected by outlook

### ISSUE THREAD

**Issue by zombiestruck** [solero/dash#21]
Sendgrid is rejected by outlook and activation email is being marked as spam.

**Comment by EmperorBale** [comment]
This is an issue with sendgrid, not dash

**Comment by daniel11420** [comment]
As Emperor said, this is an issue with SendGrid, not Dash. You can upgrade to a SendGrid paid plan to avoid this (it gives you your own IP), but other than that, there's no way to avoid it. If you use the allowed-email-hosts list feature, just make outlook emails not allowed.
