### ISSUE TITLE
[LEGACY] Puffles doing the wrong thing

### ISSUE THREAD

**Issue by santi134565** [solero/dash#43]
Hi, found this annoying bug:

you have 2 types of furniture in your igloo: puffle beds and puffle toys. You got a puffle and ask it for example sleep, the puffle instead will go to play on the toy, then you ask it to play, and it goes to sleep.

This bug is very annoying since it can reduce puffle stats, i havent found the code that manages this behaviour so i've decided to leave it here.

**Comment by AllinolCP** [comment]
why is the issue in dash it should've been in solero/houdini instead
