### ISSUE TITLE
Issue running installation

### ISSUE THREAD

**Issue by Jaskowicz1** [solero/dash#6]
Trying to do `python bootstrap.py -c config.py` is returning `Traceback (most recent call last):
  File "bootstrap.py", line 3, in <module>
    from sanic.log import logger
ImportError: No module named sanic.log`. I've tried to install it separately and sanic is returning that it's already installed.

**Comment by Blueyzachary** [comment]
Uninstall, then make sure to reinstall with `python3.8 -m pip install`

**Comment by Jaskowicz1** [comment]
`ERROR: Could not install packages due to an EnvironmentError: [Errno 30] Read-only file system: '/snap/python38/22/bin/pip'`

**Comment by Jaskowicz1** [comment]
Never mind, forgot to use python3. Sorry!
