### ISSUE TITLE
Dash can be crashed by requesting an avatar with ?size=99999

### ISSUE THREAD

**Issue by daniel11420** [solero/dash#9]
tl;dr, add a limit to ?size on /avatar/ID/cp

long version:
if you request an avatar like so: play.example.com/avatar/3/cp?size=99999 then Dash can run out of memory and crash
video of it happening: https://image-host.club/vhltsT30.mp4

**Comment by daniel11420** [comment]
even if the game would never request something this big, someone malicious could simply kill a server's dash by opening 1 url

**Comment by Zaseth** [comment]
https://github.com/solero/dash/blob/master/dash/routes/avatar.py#L22

Isn't this deprecated? https://github.com/huge-success/sanic/pull/1476/files/334b3a9cdfe3e649a770a8ba5b7cbe4b61004102

**Comment by daniel11420** [comment]
https://github.com/solero/dash/pull/10

made a pr ¯\_(ツ)_/¯

**Comment by Zaseth** [comment]
This should be closed.

**Comment by rsakeys** [comment]
#12 resolves this
